### ISSUE TITLE
PIR on GPU

### ISSUE THREAD

**Issue by ryscheng** [ryscheng/pdb#15]
http://developer.amd.com/resources/articles-whitepapers/opencl-optimization-case-study-simple-reductions/

 Just a place to track progress

**Comment by willscott** [comment]
an initial version of this exists as of 3e1b8b61970930

**Comment by willscott** [comment]
A "should-be-pretty-efficient" version of this is in progress at https://github.com/ryscheng/pdb/tree/pipelined-pir

**Comment by willscott** [comment]
Resolved by #19
